title: ProductCatalog
allOf:
  - $ref: Product.yaml
  - type: object
    properties:
      package_list:
        type: array
        items:
          $ref: Product.yaml
  - type: object
    properties:
      component_list:
        type: array
        items:
          $ref: Product.yaml
