openapi: 3.0.0
info:
  title: NT Customer API
  version: 2.0.0
  contact:
    name: Peerasak Wangsom
    email: peerasak.w@nc.ntplc.co.th
  description: Full API services for NT customer database
  license:
    name: MIT
    url: 'https://github.com/pwangsom/nt-customer-api/blob/main/LICENSE'
servers:
  - url: 'https://customerapi.cattelecom.com/dev'
    description: Development
  - url: 'https://customerapi.cattelecom.com'
    description: Production

paths:
  /customer/generate/customer_acct_number/{offset}:
      $ref: paths/utility/U01.v1.yaml
  
  '/invoice/{invoice_number}':      
      $ref: paths/invoice-payment/I01.v1.yaml