openapi: 3.0.0
info:
  title: NT Customer API
  version: 2.2.0
  contact:
    name: Peerasak Wangsom
    email: peerasak.w@nc.ntplc.co.th
  description: Full API services for NT customer database
  license:
    name: MIT
    url: 'https://github.com/pwangsom/nt-customer-api/blob/main/LICENSE'
servers:
  - url: 'https://customerapi.cattelecom.com/dev/customerapi'
    description: Development
  - url: 'https://customerapi.cattelecom.com/app/customerapi'
    description: Production

paths:
  $ref: paths/index-k2.yaml