openapi: 3.0.0
info:
  title: NT Customer API
  description: Full API services for NT customer database
  contact:
    name: Peerasak Wangsom
    email: peerasak.w@nc.ntplc.co.th
  license:
    name: MIT
    url: 'https://github.com/pwangsom/nt-customer-api/blob/main/LICENSE'
  version: 2.0.0
servers:
  - url: 'https://customerapi.cattelecom.com/dev'
    description: Development
  - url: 'https://customerapi.cattelecom.com'
    description: Production
paths:
  '/customer/generate/customer_acct_number/{offset}':
    get:
      tags: []
      summary: Get CA Number.
      description: Generate CA number
      operationId: U01
      parameters:
        - name: offset
          in: path
          description: Offset
          required: true
          style: simple
          explode: false
          schema:
            maximum: 100
            minimum: 1
            type: integer
            example: 1
      responses:
        '200':
          description: Generate success.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: CA reference number
                  format: number
                  example: '7017480851'
        '400':
          description: Bad request.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: Generate failed.
        '500':
          description: Unexpected error.
  '/billing/{bill_acct_number}/invoice':
    get:
      tags: []
      summary: Get All Invoices by BA Number.
      description: Retrieve a list of invoices by bill_acct_number
      operationId: B03
      parameters:
        - name: bill_acct_number
          in: path
          description: หมายเลข BA
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: number
            example: '12254127'
      responses:
        '200':
          description: Data Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Invoice.v1'
        '400':
          description: Bad request.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: Data was not found.
        '500':
          description: Unexpected error.
  '/billing/{bill_acct_number}/invoice/debt':
    get:
      tags: []
      summary: Get Debt Invoices by BA Number.
      description: Retrieve a list of debt invoices by bill_acct_number
      operationId: B04
      parameters:
        - name: bill_acct_number
          in: path
          description: หมายเลข BA
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: number
            example: '12254127'
      responses:
        '200':
          description: Data Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Invoice.v1'
        '400':
          description: Bad request.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: Data was not found.
        '500':
          description: Unexpected error.
  '/billing/{bill_acct_number}/invoice/{invoice_record}':
    get:
      tags: []
      summary: Get Invoices by BA Number and Desired Record.
      description: Retrieve invoice info by bill_acct_number and number of record
      operationId: B05
      parameters:
        - name: bill_acct_number
          in: path
          description: หมายเลข BA
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: number
            example: '12254127'
        - name: invoice_record
          in: path
          description: Record of Invoice
          required: true
          style: simple
          explode: false
          schema:
            maximum: 12
            minimum: 1
            type: integer
            example: 1
      responses:
        '200':
          description: Data Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Invoice.v1'
        '400':
          description: Bad request.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: Data was not found.
        '500':
          description: Unexpected error.
  '/invoice/{invoice_number}':
    get:
      tags: []
      summary: Get Invoice Info by Invoice Number.
      description: Retrieve invoice info by invoice_number
      operationId: I01
      parameters:
        - name: invoice_number
          in: path
          description: หมายเลข invoice
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: number
            example: '1225412'
      responses:
        '200':
          description: Data Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Invoice.v1'
        '400':
          description: Bad request.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: Data was not found.
        '500':
          description: Unexpected error.
  '/invoice/{invoice_number}/payment':
    get:
      tags: []
      summary: Get All Payment Trans by Invoice Number.
      description: Retrieve payment info by invoice_number
      operationId: I03
      parameters:
        - name: invoice_number
          in: path
          description: หมายเลข invoice
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: number
            example: '1225412'
      responses:
        '200':
          description: Data Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentTransaction.v1'
        '400':
          description: Bad request.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: Data was not found.
        '500':
          description: Unexpected error.
  '/invoice/{invoice_number}/payment/{tracking_id}':
    get:
      tags: []
      summary: Get a Payment Tran by Invoice Number and Tracking ID.
      description: Retrieve payment info by invoice_number and tracking_id
      operationId: I40
      parameters:
        - name: invoice_number
          in: path
          description: หมายเลข invoice
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: number
            example: '1225412'
        - name: tracking_id
          in: path
          description: หมายเลข Tracking ID
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: number
            example: '11234768'
      responses:
        '200':
          description: Data Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PaymentTransaction.v1'
        '400':
          description: Bad request.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: Data was not found.
        '500':
          description: Unexpected error.
  '/prepaid/sub/{subscriber_number}/subscription_charge/peroid/{date_from}/{date_to}':
    get:
      tags: []
      summary: Get Prepaid Subscriptions by Subscriber Number.
      description: 'Retrieve prepaid subscriptions by subscriber_number, subscription_date_from, and subscription_date_to'
      operationId: I05
      parameters:
        - name: subscriber_number
          in: path
          description: หมายเลข Subscriber
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: '882952859'
        - name: date_from
          in: path
          description: วันที่เริ่มต้นของช่วงเวลาการค้นหา
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: date
            example: '2020-06-01'
        - name: date_to
          in: path
          description: วันที่สิ้นสุดของช่วงเวลาการค้นหา
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: date
            example: '2020-06-30'
      responses:
        '200':
          description: Data Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PrepaidSubscriptionCharge.v1'
        '400':
          description: Bad request.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: Data was not found.
        '500':
          description: Unexpected error.
  '/prepaid/sub/{subscriber_number}/over_usage/peroid/{date_from}/{date_to}':
    get:
      tags: []
      summary: Get Prepaid Over Usage by Subscriber Number.
      description: 'Retrieve prepaid over usage by subscriber_number, usage_date_from, and usage_date_to'
      operationId: I06
      parameters:
        - name: subscriber_number
          in: path
          description: หมายเลข Subscriber
          required: true
          style: simple
          explode: false
          schema:
            type: string
            example: '882952859'
        - name: date_from
          in: path
          description: วันที่เริ่มต้นของช่วงเวลาการค้นหา
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: date
            example: '2020-06-01'
        - name: date_to
          in: path
          description: วันที่สิ้นสุดของช่วงเวลาการค้นหา
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: date
            example: '2020-06-30'
      responses:
        '200':
          description: Data Found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PrepaidOverUsageCharge.v1'
        '400':
          description: Bad request.
        '401':
          description: Authorization information is missing or invalid.
        '404':
          description: Data was not found.
        '500':
          description: Unexpected error.
components:
  schemas:
    Invoice.v1:
      title: Invoice
      required:
        - amount
        - due_date
        - invoice_number
        - issue_date
      type: object
      properties:
        invoice_number:
          type: string
          format: number
          example: '25856552'
        bill_acct_number:
          type: string
          description: หมายเลข BA
          format: number
          example: '23658745'
        issue_date:
          type: string
          description: วันที่ออก Invoice
          format: date
          example: '2020-06-10'
        due_date:
          type: string
          description: วันที่ครบกำหนดชำระ
          format: date
          example: '2020-06-25'
        period_from:
          type: string
          description: วันที่เริ่มต้นคิดค่าบริการ (วันที่เริ่มต้นรอบบิล)
          format: date
          example: '2020-05-01'
        period_to:
          type: string
          description: วันที่สิ้นสุดคิดค่าบริการ (วันที่สิ้นสุดรอบบิล)
          format: date
          example: '2020-05-31'
        amount:
          type: number
          description: ยอดหนี้ไม่รวม VAT
          format: double
          example: 590
        vat:
          type: number
          description: VAT
          format: double
          example: 41.3
        paid_amount:
          type: number
          description: ยอดชำระรวม VAT
          format: double
          example: 0
        last_paid_date:
          type: string
          description: วันที่ชำระเงินล่าสุด
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        balance_amount:
          type: number
          description: ยอดหนี้คงค้างรวม VAT
          format: double
          example: 590
        balance_update_date:
          type: string
          description: วันที่เปลี่ยนแปลงยอด balance_amount ล่าสุด
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        invoice_sub_list:
          type: array
          items:
            $ref: '#/components/schemas/InvoiceSubscriber.v1'
      description: Invoice model
      x-tags:
        - Invoice
    InvoiceSubscriber.v1:
      title: InvoiceSubscirber
      required:
        - amount
        - invoice_number
        - ref_subscr_no
      type: object
      properties:
        invoice_number:
          type: string
          format: number
          example: '25856552'
        ref_subscr_no:
          type: string
          format: number
          example: '25412'
        amount:
          type: number
          description: ยอดหนี้ไม่รวม VAT
          format: double
          example: 590
      description: Invoice subscriber model
    PaymentTransaction.v1:
      title: PaymentTransaction
      required:
        - invoice_number
        - tracking_id
      type: object
      properties:
        tracking_id:
          type: string
          description: payment transaction id
          format: number
          example: '25856552'
        invoice_number:
          type: string
          format: number
          example: '25856552'
        pay_date:
          type: string
          format: date
          example: '2020-06-10'
        amount:
          type: number
          description: ยอดชำระ
          format: double
          example: 590
        vat:
          type: number
          format: double
          example: 41.3
        location:
          type: string
          description: สถานที่รับชำระ
          example: ศูนย์บริการลูกค้าสุขุมวิท
        receipt_id:
          type: string
          description: เลขที่ใบเสร็จ
          example: '25856552'
      description: Payment transaction model
    PrepaidOverUsageCharge.v1:
      title: PrepaidOverUsageCharge
      required:
        - amount
        - subscriber_number
        - usage_date
      type: object
      properties:
        usage_date:
          type: string
          format: date
          example: '2020-06-10'
        ref_subscr_no:
          type: string
          format: number
          example: '25856552'
        subscriber_number:
          type: string
          example: '0882543698'
        amount:
          type: number
          description: ยอดเงินการใช้จ่ายส่วนเกิน
          format: double
          example: 50
      description: PrepaidOverUsageCharge
    PrepaidSubscriptionCharge.v1:
      title: PrepaidSubscriptionCharge
      required:
        - amount
        - charge_type
        - offer_id
        - subscriber_number
        - subscription_date
        - subscription_id
      type: object
      properties:
        subscription_id:
          type: string
          example: U2003010000075937752
        subscription_date:
          type: string
          format: date
          example: '2020-06-10'
        ref_subscr_no:
          type: string
          format: number
          example: '25856552'
        subscriber_number:
          type: string
          example: '0882543698'
        offer_id:
          type: string
          description: รหัสโปรโมชั่น
          format: number
          example: '51006022'
        offer_name:
          type: string
          description: ชื่อโปรโมชั่น
          example: เน็ตสุดคุ้ม 1 Mbps. 279
        amount:
          type: number
          description: ยอดเงินสมัครโปรโมชั่น
          format: double
          example: 50
        charge_type:
          type: string
          description: 'ประเภทการ Charge (NRC, RC)'
          example: RC
      description: Prepaid subscription charge model
  parameters:
    BillAcctNumber.v1:
      name: bill_acct_number
      in: path
      description: หมายเลข BA
      required: true
      style: simple
      explode: false
      schema:
        type: string
        format: number
        example: '12254127'
    DateFrom.v1:
      name: date_from
      in: path
      description: วันที่เริ่มต้นของช่วงเวลาการค้นหา
      required: true
      style: simple
      explode: false
      schema:
        type: string
        format: date
        example: '2020-06-01'
    DateTo.v1:
      name: date_to
      in: path
      description: วันที่สิ้นสุดของช่วงเวลาการค้นหา
      required: true
      style: simple
      explode: false
      schema:
        type: string
        format: date
        example: '2020-06-30'
    InvoiceNumber.v1:
      name: invoice_number
      in: path
      description: หมายเลข invoice
      required: true
      style: simple
      explode: false
      schema:
        type: string
        format: number
        example: '1225412'
    InvoiceRecord.v1:
      name: invoice_record
      in: path
      description: Record of Invoice
      required: true
      style: simple
      explode: false
      schema:
        maximum: 12
        minimum: 1
        type: integer
        example: 1
    Offset.v1:
      name: offset
      in: path
      description: Offset
      required: true
      style: simple
      explode: false
      schema:
        maximum: 100
        minimum: 1
        type: integer
        example: 1
    SubscriberNumber.v1:
      name: subscriber_number
      in: path
      description: หมายเลข Subscriber
      required: true
      style: simple
      explode: false
      schema:
        type: string
        example: '882952859'
    TrackingId.v1:
      name: tracking_id
      in: path
      description: หมายเลข Tracking ID
      required: true
      style: simple
      explode: false
      schema:
        type: string
        format: number
        example: '11234768'
