title: Package
allOf:
  - type: object
    properties:
      package_id:
        type: string
        format: number
        example: '13654'
        description: Package reference number
      component_list:
        type: array
        items:
          $ref: Component.yaml
    required:
      - package_id
  - $ref: DisplayProduct.yaml
x-tags:
  - Package
